version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: your_image_name
    container_name: app_container_name
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - your_network
  db:
    image: mysql:5.7
    container_name: db_container_name
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
      MYSQL_PASSWORD: db
      MYSQL_USER: db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - your_network
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx_container_name
    restart: unless-stopped
    ports:
      - 50003:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - your_network
  pma:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: pma_container_name
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 50004:80
    networks:
      - your_network

networks:
  your_network:
    driver: bridge

volumes:
  dbdata:
    driver: local